### PR TITLE
Make options object optional

### LINKED ISSUE #4: Make options optional
```js
this.fileManager = cdn.create('S3', {
      auth: {
        AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
        AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
        AWS_REGION: process.env.AWS_REGION
      }
    });
```
If I don't pass the `option` object in the `create()` function, it will end up with an error:
```
/node_modules/file-management/src/providers/s3.js:16
      maxRetries: config.options.maxRetries || 1,
                                 ^

TypeError: Cannot read property 'maxRetries' of undefined
    at new S3Provider (/node_modules/file-management/src/providers/s3.js:16:34)
    at Object.createProvider (/node_modules/file-management/src/providers/factory.js:36:14)
    at Object.module.exports.create (/node_modules/file-management/src/index.js:13:42)
```

So, currently, to avoid it, I need to pass an empty object each time
```js
this.fileManager = cdn.create('S3', {
      auth: {
        AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
        AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
        AWS_REGION: process.env.AWS_REGION
      },
      options: {}  <-- this one
    });
```

### PR DESCRIPTION
**Pull request by steven-heng**
This PR will fix, the issue about the optional `options` object.
Resolves #4

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -10,7 +10,7 @@ const defaultConfig = require('./providers/config').create();
  */
 module.exports.create = (provider = 'default', config = defaultConfig) => {
   assert(provider, 'A provider must be specified');
-  const activeProvider = providerFactory.createProvider(provider, config);
+  const activeProvider = providerFactory.createProvider(provider, Object.assign({ options: {} }, config));
   /**
```
Comment (ykhatal) [inline src/index.js:14]: There is a space after config

File: test/index.js [hunk 2]
```diff
@@ -53,4 +53,21 @@ describe('Mock Provider', () => {
 
     it('to delete a file', () => manager.deleteFile(testFile));
   });
+
+  describe('should work without options', () => {
+    it('', () => {
```
Comment (ykhatal) [inline test/index.js]: missing message

File: test/intergration/.env [hunk 3]
```diff
@@ -1,4 +1,4 @@
 # for s3 provider
 AWS_ACCESS_KEY_ID=
 AWS_SECRET_ACCESS_KEY=
-AWS_REALM=eu-central-1
+AWS_REGION=eu-central-1
```
Comment (ky23) [inline test/intergration/.env]: ### Question

@mrister Do we still need the `AWS_REALM` ?

**Review by ykhatal — CHANGES_REQUESTED** [review]

File: src/index.js (hunk 1 above)
Comment (ykhatal) [reply src/index.js:14]: sorry don't take this one in account, i though it was an object

**Review by ykhatal — APPROVED** [review]
First PR validated 🎖

File: test/intergration/.env [hunk 4]
```diff
@@ -1,4 +1,4 @@
 # for s3 provider
 AWS_ACCESS_KEY_ID=
 AWS_SECRET_ACCESS_KEY=
-AWS_REALM=eu-central-1
```
Comment (mrister) [inline test/intergration/.env:4]: @ky23 sorry accidentally deleted your question, I think AWS_REGION is unused and can be removed..not sure how it got in there...

**Review by mrister — APPROVED** [review]
tests should be fixed

File: test/intergration/.env (hunk 4 above)
Comment (steven-heng) [reply test/intergration/.env]: The tests are passed but there is a problem in the sonar configuration, 
I will fix it

File: test/intergration/provider-s3.js [hunk 5]
```diff
@@ -58,4 +58,21 @@ describe('S3 Provider', () => {
 
     it('to delete a file', () => manager.deleteFile(testLocation, testFileName));
   });
+
+  describe('should initialize S3 provider without options', () => {
```
Comment (Spring3) [inline test/intergration/provider-s3.js]: More of a tip, than some mistake, but in `describe(` you usually want to write something like the name of the tool or a class that you test and then in the `it(` you write what it should/should not do. This works so, that when running a test, the message is taken from the `describe(` function and then added before each message inside teh `it(` function. So if you have, for example, the following test:
```
describe('My laptop', () => {
  it('should be able to charge', () => {});
  it('should be able to write code for me', () => {});
  it('should be able to look for pictures of cats when I'm sad', () => {});
})
```
it will result in the following console output:
```
✓ My laptop should be able to charge
✓ My laptop should be able to write code for me
✓ My laptop should be able to look for pictures of cats when I'm sad
```
You see? So it takes that string from the `describe(` function and appends it to the string from `it` function and altogether, it is combined into a readable test case.

In your case, it will be 
`should initialize S3 provider without options should work without options`

Not very clear, right?
So, if you can, please adjust it to make it look perfect.

**Review by Spring3 — APPROVED** [review]

File: test/intergration/provider-s3.js (hunk 5 above)
Comment (steven-heng) [reply test/intergration/provider-s3.js]: Very well, thank you for enlightening me on this subject, 
I will rectify this immediately.

**Review by mrister — APPROVED** [review]

**Review by jkernech — APPROVED** [review]
Nice one, Please squash your commits before merging this PR
